name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["Phantomojo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Critical - System crash or data loss
        - High - Major functionality broken
        - Medium - Minor functionality affected
        - Low - Cosmetic issue or minor annoyance
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Component
      description: Which component is affected?
      options:
        - API/Backend
        - Trading Engine
        - Risk Management
        - Data Ingestion
        - AI Models
        - Dashboard/Frontend
        - Database
        - Docker/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📋 Version
      description: What version of the system are you using?
      placeholder: e.g., v1.2.3, main branch, commit hash
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 💻 Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - macOS
        - Windows
        - Docker Container
        - Other
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: 🐍 Python Version
      description: What Python version are you using?
      placeholder: e.g., 3.11.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📊 Logs and Error Messages
      description: Please include any relevant logs, error messages, or stack traces
      placeholder: |
        ```
        [ERROR] 2025-08-31 15:30:00 - Database connection failed
        Traceback (most recent call last):
          File "src/main.py", line 45, in <module>
            ...
        ```
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Any other context about the problem
      placeholder: |
        - Screenshots (if applicable)
        - Environment variables
        - Configuration files
        - Related issues
        - Workarounds you've tried

  - type: checkboxes
    id: terms
    attributes:
      label: 📋 Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: This is not a security vulnerability (use SECURITY.md for those)
          required: true
