name: 🛡️ Security Vulnerability
description: Report a security vulnerability (DO NOT post publicly)
title: "[SECURITY] "
labels: ["security", "vulnerability", "confidential"]
assignees: ["Phantomojo"]
body:
  - type: markdown
    attributes:
      value: |
        🚨 **SECURITY VULNERABILITY REPORT** 🚨
        
        **IMPORTANT**: This issue will be kept private and confidential.
        Please provide detailed information to help us address the vulnerability quickly and effectively.

  - type: textarea
    id: vulnerability_type
    attributes:
      label: 🎯 Vulnerability Type
      description: What type of security vulnerability is this?
      placeholder: |
        - SQL Injection
        - Cross-Site Scripting (XSS)
        - Authentication Bypass
        - Information Disclosure
        - Privilege Escalation
        - Remote Code Execution
        - Denial of Service
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical - Immediate action required, potential for data loss/system compromise
        - High - Significant security impact, requires prompt attention
        - Medium - Moderate security impact, should be addressed soon
        - Low - Minor security impact, can be addressed in regular updates
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Vulnerability Description
      description: Provide a clear and detailed description of the vulnerability
      placeholder: |
        Describe the vulnerability in detail:
        - What is the issue?
        - How does it work?
        - What are the potential impacts?
        - Which components are affected?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 💥 Potential Impact
      description: What could an attacker do with this vulnerability?
      placeholder: |
        - Data exposure
        - System compromise
        - Financial loss
        - Reputation damage
        - Compliance violations
        - Other impacts
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: |
        1. [Step 1]
        2. [Step 2]
        3. [Step 3]
        4. [Expected vs Actual Result]
        
        Include any required tools, scripts, or commands.
    validations:
      required: true

  - type: textarea
    id: proof_of_concept
    attributes:
      label: 🔬 Proof of Concept
      description: Provide a proof of concept (code, commands, screenshots)
      placeholder: |
        ```
        # Example exploit code or commands
        curl -X POST "http://localhost:8000/api/v1/..." \
          -H "Content-Type: application/json" \
          -d '{"malicious": "payload"}'
        ```
        
        **Note**: Do not include actual exploit code that could be harmful.
    validations:
      required: true

  - type: input
    id: affected_versions
    attributes:
      label: 📋 Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: e.g., v1.0.0, v1.1.0, all versions before v1.2.0
    validations:
      required: true

  - type: dropdown
    id: affected_components
    attributes:
      label: 🧩 Affected Components
      description: Which components are affected?
      options:
        - API/Backend
        - Trading Engine
        - Risk Management
        - Data Ingestion
        - AI Models
        - Dashboard/Frontend
        - Database
        - Docker/Deployment
        - Authentication/Authorization
        - Multiple Components
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 💻 Environment Details
      description: Environment where the vulnerability was discovered
      placeholder: |
        - Operating System: [OS and version]
        - Python Version: [Python version]
        - Dependencies: [Key dependencies and versions]
        - Configuration: [Any relevant configuration]
        - Network: [Local/Remote, Firewall settings, etc.]
    validations:
      required: true

  - type: textarea
    id: suggested_fix
    attributes:
      label: 🔧 Suggested Fix
      description: Do you have any suggestions for fixing this vulnerability?
      placeholder: |
        - Recommended approach
        - Code changes needed
        - Configuration changes
        - Security best practices to follow
    validations:
      required: false

  - type: textarea
    id: timeline
    attributes:
      label: ⏱️ Disclosure Timeline
      description: When do you plan to disclose this vulnerability publicly?
      placeholder: |
        - Immediate disclosure
        - After fix is deployed
        - Coordinated disclosure
        - No public disclosure planned
        - Other timeline
    validations:
      required: true

  - type: textarea
    id: contact
    attributes:
      label: 📞 Contact Information
      description: How can we contact you for follow-up questions?
      placeholder: |
        - Email: [your-email@domain.com]
        - GitHub: [your-github-username]
        - PGP Key: [if you have one]
        - Other contact method
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 📋 Security Report Terms
      description: Please confirm the following
      options:
        - label: I will not publicly disclose this vulnerability until it's fixed
          required: true
        - label: I have provided accurate and complete information
          required: true
        - label: I understand this report will be kept confidential
          required: true
        - label: I will cooperate with the security team if needed
          required: true
