# Forex Trading System Credentials
# IMPORTANT: This file contains sensitive API keys
# DO NOT commit this file to version control
# Use environment variables in production

# OANDA API Configuration
oanda:
  api_key: "1725da5aa30805b09b7c7eb0094ffff4-d6b1be348877531faa9a3253cbda3cfd"
  account_id: ""  # Add your OANDA account ID here
  environment: "practice"  # practice or live
  base_url: "https://api-fxpractice.oanda.com"

# News API Configuration
news_api:
  api_key: "a025383ef4974ff1a52d6d0484db191a"
  enabled: true
  sources: ["reuters", "bloomberg", "cnbc", "bbc-news"]

# Finnhub API Configuration
finnhub:
  api_key: "d2q0r71r01qnf9nn12r0d2q0r71r01qnf9nn12rg"
  secret: "d2q0r71r01qnf9nn12sg"
  enabled: true

# Alpha Vantage API Configuration
alpha_vantage:
  api_key: "HY5M3D5IDQ6UIC0Z"
  enabled: true

# X (Twitter) API Configuration
x_api:
  api_key: "EHdQ8vvVuZHxbnGq9OS4nAb7clftr2fLzgCNrus35n7xposOog"
  api_secret: "PgiluRTUYdddkHS9m9Gd8DOQ1"
  bearer_token: "AAAAAAAAAAAAAAAAAAAAAHF83wEAAAAAO0Ux7eeHiNmlc4n6tobA%2FDhZTnY%3DSl1M9ZeWNmiO9VXUZxh2SGjfWB5JUP3ujjQisYLHoLSChg8aYn"
  access_token: "1600201538659549208-DXlOHsC0pQ1G3kG1zbu9ikSjKnxZMx"
  access_token_secret: "kWev78Vu8rbJWe1J1e8zHXV78tFx2KoyRhuUYFRLBMjur"
  enabled: true

# NASDAQ Data API Configuration
nasdaq:
  api_key: "bArm_eYp_sjHRvCjRz7T"
  enabled: true

# Economic Calendar APIs
economic_calendar:
  forex_factory_enabled: true
  investing_com_enabled: true
